### ISSUE TITLE
Crash appears on some mobile phones when  other dissconnect session ,Disconnect owner session 

### ISSUE THREAD

**Issue by Jonniu** [opentok/opentok-android-sdk-samples#236]
(com.opentok.android.v3.Subscriber.close+24)
2019-08-05 22:06:11.249 3400-3400/? A/DEBUG:     #17 pc 000000000017c998  /dev/ashmem/dalvik-classes2.dex extracted in memory from /data/app/com.commongenius.android.debug--Ne-A0CcXwctJXSj3P8Vjw==/split_lib_dependencies_apk.apk!classes2.dex (deleted) (com.opentok.android.v3.Session.onDisconnected+64)

**Comment by jintgeorge** [comment]
We are aware of this issue and working on the fix. Hoping to get it released asap. Thanks !

**Comment by mark-veenstra** [comment]
@jintgeorge Any news on the SDK update fixing this crash?

**Comment by Jonniu** [comment]
@jintgeorge @robjperez

**Comment by robjperez** [comment]
Sorry for the delay having the patch ready.
We are working in the fix and we will be releasing a new version of the Android SDK soon

**Comment by nataliia-zarudna** [comment]
Hello.
We are facing the same issue and cannot upgrade to 2.16.1 version because of it. Are there any estimation when it will be fixed? Thanks.

**Comment by mark-veenstra** [comment]
@robjperez @msach22 Any updates on the Android SDK release, we are still using 2.14+ version, because 2.15+ and 2.16+ all are unstable to use. But some issues in the 2.14+ are solved in the 2.15+ and 2.16+, but we just can;'t use it, because in our situation all users would crash due to the unstability and crashes reported here...

We are talking about a SDK release for some time now. Please share a real estimated time for the release since it is blocking us now...

**Comment by msach22** [comment]
@mark-veenstra Apologies for the delay. We released the 2.16.3 patch earlier today.

**Comment by shahalRahman** [comment]
Facing the same issue in 2.16.3 as well.
`signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x70`

**Comment by shakil807g** [comment]
@shahalRahman Have you found any solution to this issue ? @jintgeorge  I'm using 2.16.3 and found some time app freeze

**Comment by msach22** [comment]
Hi all, in the past few releases, we've fixed some more crash issues. I recommend trying out 2.16.6 and see if you are still getting this similar behavior. For more info, please see release notes: https://tokbox.com/developer/sdks/android/release-notes.html

**Comment by ami9000** [comment]
Still experiencing the random crash on 2.16.6 when android disconnects from a live session...

**Comment by shakil807g** [comment]
@robjperez @msach22 @jintgeorge Facing the same issue in 2.16.6 but worse part is. it freeze the whole app after the crash.

**Comment by robjperez** [comment]
@shakil807g @ami9000 @shahalRahman can you test with 2.17.0 ?

**Comment by shakil807g** [comment]
@robjperez  The issue was ConcurrentModificationException thrown some time when calling Session.disconnect on 2.16.6, which freeze the whole app and users have to restrart the whole device or force stop.

**Comment by robjperez** [comment]
All that code has been refactored for 2.17, so please try with the new version, the issue should be gone.
